server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /usr/share/nginx/html;
    index hub.html;

    # ─── Hub principal ────────────────────────────────────
    location = / {
        try_files /hub.html =404;
    }

    location /api/ {
    proxy_pass http://friday:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

    # ─── Fichiers statiques ───────────────────────────────
    location / {
        try_files $uri $uri/ =404;
    }

    # ─── Gzip ─────────────────────────────────────────────
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;

    # ─── Cache assets ─────────────────────────────────────
    location ~* \.(css|js|png|jpg|ico|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
